theme = "hugo-kiera"
baseURL = 'https://www.computermediatedmonologue.com'
languageCode = 'en-us'
title = 'A Computer Mediated Monologue'
publishdir = './docs/'

[author]

	name = "RichR"
	linkedin = "richard-roberts-9b3b25228"
